### ISSUE TITLE
Circuit diagram

### ISSUE THREAD

**Issue by soo246** [edgardogho/StepGenerator#1]
Of this firmware
Can you know the schematic?

**Comment by edgardogho** [comment]
I have no schematic drawn for it, but its a fairly simple circuit...
#define encoderClick 2
#define encoderA 3
#define encoderB 4
#define outputPin 5
#define diroutPin 6
#define runPin 7
#define sensorPin 11
#define manualPin 9
#define dirinPin 8

The encoder is a standar digital arduino encoder like: https://www.amazon.com/Cylewet-Encoder-15%C3%9716-5-Arduino-CYT1062/dp/B06XQTHDRR/ref=sr_1_3?dchild=1&keywords=arduino+encoder&qid=1619132133&sr=8-3

The sensorPin is connected to a proximity sensor like: https://www.amazon.com/Twidec-Normally-inductive-Proximity-LJ12A3-4-Z/dp/B07NYD4MVC/ref=sr_1_8?dchild=1&keywords=arduino+sensor+inductance&qid=1619132190&sr=8-8

The output pin and direction pin drive a stepper motor driver: https://www.amazon.com/Stepper-Bracket-TB6600-Controller-Printer/dp/B07RQTWLMQ/ref=sr_1_2_sspa?dchild=1&keywords=stepper+motor+driver&qid=1619132246&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFDUVhYQUxTU0VEQzImZW5jcnlwdGVkSWQ9QTAxMjY3NjkzODJENEoxTUVFVTRaJmVuY3J5cHRlZEFkSWQ9QTAzMTgyMjNYWERaNzc2OUdDVDMmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl

The LCD is an i2c 16x2 alphanumeric: https://www.amazon.com/dp/B07PFBDDYB/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B07PFBDDYB&pd_rd_w=Ey1wr&pf_rd_p=085568d9-3b13-4ac1-8ae4-24a26c00cb0c&pd_rd_wg=LAptX&pf_rd_r=D4J9W5QGMG84W69Q99FQ&pd_rd_r=8c6500c1-0c52-4dde-975f-99b4baef72b4&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExMjlNQU45SU1GMUMwJmVuY3J5cHRlZElkPUEwMDcwMjkyMlZEUTBFTFpYVjdaJmVuY3J5cHRlZEFkSWQ9QTA0MTQyMTMyQUxRQlJCRlVYWVAzJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

The rest (manualPin , dirinpin) are just standard pushbuttons.

Let me know if you have any question.
